### ISSUE TITLE
Show amino acids that have been filtered out due to negative functional score

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#102]
Can we indicate somehow on the heatmap when the mutation is filtered out because of low functional score as opposed to being greyed out as if it was not sampled in the library.

**Comment by jbloom** [comment]
Is being addressed in new version 3.4 of `polyclonal` via resolution of [this issue](https://github.com/jbloomlab/polyclonal/issues/144).
