### ISSUE TITLE
Rename prob_escape in pipeline to be more descriptive of calculation normalizing counts to neut standard control

### ISSUE THREAD

**Issue by anloes** [dms-vep/dms-vep-pipeline#117]
I suggest that we change the name for the prob_escape function. The calculation that we are denoting as "prob_escape" is computing a relative fraction infectivity normalized to a neutralization standard control, not a probability for escape compared to the non-mutagenized control protein, and I think this may be misleading. I suggest that we update the naming for this column/calculation in the package to better reflect what this calculation is doing, perhaps a shortened version of "relative fraction infectivity" or "non-neutralized fraction"?

**Comment by jbloom** [comment]
Looking at this more, I think I am going to close this issue for now.

I agree that *fraction infectivity* is a better terminology and is what we should probably use in papers and should have used in the pipeline. However, at this point the original terminology of "prob escape" is baked into the pipeline, and it will cause all sorts of backwards incompatibility issues to change it.

I agree with the spirit of the suggestion, but I only think it is worthwhile to change this when we do a full re-write of this pipeline (or create a new pipeline), at which point *fraction infectivity* is clearly a better term. But I don't think it's worth the problems it will cause to try to rename throughout this pipeline at this time.
