### ISSUE TITLE
A few suggestions for "Functional effects of mutations averaged across replicates" page

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline#118]
If people are running multiple different kinds of functional selections, there is no way to view a subset of the libraries average effects. This would be useful for comparing how different types of functional selections are changing the inferred functional scores. Would it be possible to add in a dropdown bar where specific libraries can be included, rather than automatically including every single run that's ever been done?

Also, I believe right now most people are specifying "median" instead of "mean" for looking at the combined effects across multiple libraries. Small semantic issue but maybe the title of this page should be changed to "Functional effects of mutations across replicates"?

**Comment by jbloom** [comment]
The change of the title to be "Functional effects of mutations across replicates" and remove the word *average* is implemented in #127.

The rest of the issue is not yet addressed.
