### ISSUE TITLE
Do not rerun pacbio alignments

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#120]
Sometimes when `dms-vep` version get's updated snakemake needs to rerun the whole pipeline even if nothing changes in pacbio data. Is it possible to somehow avoid rerunning pacbio alignments again, which take a long time.

**Comment by jbloom** [comment]
@Bernadetadad (also maybe relevant to @caelanradford @bblarsen-sci @Caleb-Carr), this pull request sets up (in version 1.6.1 of `dms-vep-pipeline`) the ability to use an existing codon-variant table.

The idea is that if you have already done the PacBio analysis, then you should not need to re-run that to build the variants for each repo, but can just specify the location of an existing codon-variant table for this library.

To use this, I recommend re-organizing your `config.yaml` as [here](https://github.com/dms-vep/dms-vep-pipeline/blob/main/test_example/config.yaml#L22-L60) to move all the PacBio related params to one section.

Then if you want to use an existing codon-variant table and associated gene, just specify their URLs with `prebuilt_variants` and `prebuilt_geneseq`, and you can get rid of the other PacBio parameters.

An example of a repo that does this is in its `config.yaml` is [here](https://github.com/dms-vep/SARS-CoV-2_BA.1_spike_DMS_12-19/blob/main/config.yaml#L22-L38) (it re-uses @Bernadetadad's prior PacBio linking for BA.1 libraries). If you look at the results for that repo, it now no longer shows the PacBio variant building as this done in the BA.1 repo from which the variant table is taken.

@Bernadetadad, this should to some degree fix the re-running of PacBio alignments that you were complaining about in this issue.

However, that re-running will still happen for repos that do build those variants if the `conda` environment is updated. Right now this can only be solved with rule-specific environments, which I haven't implemented yet.
