### ISSUE TITLE
pre-built functional scores

### ISSUE THREAD

**Issue by jbloom** [dms-vep/dms-vep-pipeline#123]
@Bernadetadad, I'm just raising this issue now so we can discuss before I make changes.

Right now the functional scores for each repo are computed just from the no-antibody controls in that repo. This works well under the model where we keep a single running repo of everything. It doesn't work so well when we are having to branch off a repo for each study, as then sometimes a single antibody repo (like the *12-19* one) only has a few no-antibody controls and so is using different and probably less accurate functional scores than estimated using more replicates.

How do we fix this? Do we allow an option to access an external pre-computed set of functional scores from a larger experiment?

**Comment by Bernadetadad** [comment]
That's a good point. of course I could just copy all vsvg/no_antibody samples to each new repo split. But if we decide to allow access to external repo then we should maybe do so for codon-variant table as well.

**Comment by jbloom** [comment]
Yes, re-use of existing codon-variant tables is already enabled in #121.

I will work on allowing similar for functional scores.

**Comment by jbloom** [comment]
Here is an example of a repo that uses the pre-built mutation effects via `prebuilt_muteffects`: https://github.com/dms-vep/SARS-CoV-2_Omicron_BA.1_spike_DMS_12-19/
