### ISSUE TITLE
Epitope color change

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#138]
Would be good to add an easy way in the `dms-vep` pipeline to change the default epitope colors.

**Comment by jbloom** [comment]
@Bernadetadad, this is enabled in version 2.2.0. Just add `epitope_colors` as a list of the colors (needs to be at least as long as the list of epitopes) in `polyclonal_config` for that antibody. Such as [here](https://github.com/dms-vep/dms-vep-pipeline/blob/e76758935bfd01fd7b8d00c86424a20789526bc0/test_example/data/polyclonal_config.yaml#L42).

If you wanted same color scheme for all you would add under the `overall_default` in the `polyclonal_config`.

Colors can be specified by names or hex codes. The current defaults if you don't specify this are [here](https://github.com/jbloomlab/polyclonal/blob/main/polyclonal/plot.py#L34-L35).
