### ISSUE TITLE
Error when any neut standard barcodes have 0 counts

### ISSUE THREAD

**Issue by fwelsh** [dms-vep/dms-vep-pipeline#140]
I'm testing use of an RNA oligo spike-in as a neutralization standard, rather than a distant HA standard. This oligo was generated carrying a small pool of random barcodes. There are around 30 with appreciable counts, plus 100 additional barcodes that are at low counts in the starting pool. Most of these low-count barcodes have 0 counts in the experimental infections.

When neut std barcodes with 0 counts in selections or no-antibody controls, I get the following error in `analyze_variant_counts.ipynb`:

```
---------------------------------------------------------------------------
Exception encountered at "In [27]":
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[27], line 10
      8 print(f"Checking counts in {f}")
      9 assert os.path.isfile(f), f"cannot find {f}"
---> 10 pd.testing.assert_frame_equal(
     11     pd.read_csv(f, na_filter=None),
     12     df[
     13         [
     14             "barcode",
     15             "count",
     16             "codon_substitutions",
     17             "aa_substitutions",
     18             "variant_call_support",
     19         ]
     20     ]
     21     .sort_values(["count", "barcode"], ascending=[False, True])
     22     .reset_index(drop=True),
     23 )

    [... skipping hidden 3 frame]

File /fh/fast/bloom_j/computational_notebooks/fwelsh/2022/flu_h3_hk19_dms/.snakemake/conda/bb5f41463c0aaea8c7a58ab8a9cd0d49_/lib/python3.11/site-packages/pandas/_testing/asserters.py:679, in raise_assert_detail(obj, message, left, right, diff, index_values)
    676 if diff is not None:
    677     msg += f"\n[diff]: {diff}"
--> 679 raise AssertionError(msg)

AssertionError: Attributes of DataFrame.iloc[:, 1] (column name="count") are different

Attribute "dtype" are different
[left]:  int64
[right]: object

```

`variants.variant_count_df` has `count` as type `obj`, I'm not sure where this happens but I'm guessing that having some neut_std_barcodes with count=0 is the root of the error.

If I remove any neut_std barcodes with 0 counts in any sample and re-run the pipeline, I no longer run into this error. This is an easy temporary fix. But if we continue using an external spike-in, it would be helpful to fix this issue, so that we can just assign the full barcode pool to `neutralization_standard_barcodes.csv` without having to edit based on selection data. @jbloom

**Comment by jbloom** [comment]
@fwelsh, strangely, I cannot reproduce this error. Can you point me to current commit of repo that is giving problem and I will re-run to see if I can understand what is going on.

**Comment by fwelsh** [comment]
@jbloom [Here](https://github.com/dms-vep/flu_h3_hk19_dms/commit/23064b5079b25ab653b2e4d6f70b0e6bda384194) is the commit where I added all 127 spike-in barcodes as the neut standard. All the relevant commits are on branch `spike-in-tests` as I don't want to merge these into main. Let me know if you need any additional info!

**Comment by jbloom** [comment]
@fwelsh, this is now fixed in latest version of pipeline.
