### ISSUE TITLE
Accommodate multiple options for neut_std_barcode source

### ISSUE THREAD

**Issue by fwelsh** [dms-vep/dms-vep-pipeline#141]
Tests of the exogenous RNA spike-in standard look very promising so far. My plan is to continue using H6 as the standard for potent samples that do not neutralize H6 at selection concentrations. For less potent samples, I will normalize using this spike-in control. 

It would be helpful to have an option for multiple labeled `neutralization_standard_barcodes.csv` inputs (or a single file, with labeled sets of barcodes for different standards). Then, in the `barcode_runs.csv` input, we can add an optional column to specify which neut standard that sample should be normalized against. 

I've only tested the RNA spike-in against a single serum, and results were very promising but not conclusive yet. I'm getting data back tonight from a followup run where I tested the RNA spike-in standard with 5 different sera, which should provide more definitive results. But just wanted to put this on your radar for now @jbloom

**Comment by jbloom** [comment]
I will work on this!

**Comment by jbloom** [comment]
@fwelsh, you can do this. Please see the explanation in #143 for details.
