### ISSUE TITLE
Add slider to filter heat-maps based on escape_std

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#148]
Sometimes it would be nice to be able to filter out from heat-maps sites that have very large `escape_std`, especially when picking sites to validate. Could we add a slider that does that? I know we stopped displaying `escape_std` in some version of `dms-vep` and now only display measurements for each library.

**Comment by jbloom** [comment]
Closed in favor of #153, which should accomplish a similar goal.
