### ISSUE TITLE
minimum max of escape slider should depend on functional effect value

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#149]
The `minimum max of escape` slider still includes the sites that have been filtered out due to functional effects, can we set it so that it would only show the sites that it are above whatever functional threshold is set?

**Comment by jbloom** [comment]
This is fixed in `polyclonal` 5.2, which still needs to be updated in this pipeline:
https://github.com/jbloomlab/polyclonal/commit/55c15989324ed8024afa21eab39568487c6fbf1b
