### ISSUE TITLE
Give option to inspect antibody selection scores by concentration rather than solely averaged across replicates

### ISSUE THREAD

**Issue by bblarsen-sci** [dms-vep/dms-vep-pipeline#151]
If someone does a selection on a library with multiple concentrations of antibody, the pipeline currently reports the average of each of these conditions. As discussed in [this](https://jbloomlab.slack.com/archives/C7838LPGF/p1677186641156809) thread, sometimes it is necessary to only use a single selection concentration to reduce noise. Also, people often run selections with a broad range of antibody conditions but end up only using one. Right now, it is possible to deal with this by rerunning entire pipeline and either removing the antibody conditions that aren't used, or add "yes" to the "exclude_after" column in `barcode_runs.csv`. This can be somewhat tedioius. I think it would be useful to be able to split out the concentrations in 'Antibody-escape averaged across replicates' /docs page so they can be individually inspected and compared, rather than automatically lumped together.

**Comment by Bernadetadad** [comment]
Would this not make pipeline run even longer as now it would have to do the modeling for each concentration and all possible combinations of concentrations? 

I would suggest just running interactively and testing different sets of concentrations that way. Attached is a notebook that I use to do this.
[360C_sera_modeling.ipynb.zip](https://github.com/dms-vep/dms-vep-pipeline/files/11151457/360C_sera_modeling.ipynb.zip)

**Comment by bblarsen-sci** [comment]
That's true about the runtime....Maybe it could be an option in the config file whether you want to or not? Yes, I agree on doing it iteratively, and thanks for sharing the script! I still think it would be nice to just have the pipeline do it all in one go though rather than having to go in and running separately. I'll leave it up to @jbloom if worth effort or not, I'm fine either way.
