### ISSUE TITLE
Option to display by the smaller escape value

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#153]
@jbloom I think it would actually be nice to have an option to display the smaller of the two replicate escape values on the heatmaps. Maybe this could be added to `.config` as an option in addition of median/mean that are available now.

**Comment by jbloom** [comment]
Can be addressed after `polyclonal` 5.3 version is created with this change: https://github.com/jbloomlab/polyclonal/pull/163

**Comment by jbloom** [comment]
@Bernadetadad, This will be enabled in version 2.5.0, which should be available shortly. 

You can set `avg_type: min_magnitude` under `plot_kwargs` in the `polyclonal_config.yaml` file, and that will display the escape value with the minimum overall magnitude (absolute value) across models for each mutation.

**Comment by Bernadetadad** [comment]
@jbloom `min_magnitude` only works if replicates have escape values that are both either positive or both negative but not if one value is negative and the other is positive.
<img width="183" alt="image" src="https://user-images.githubusercontent.com/22810662/232377747-df0f4441-4473-4695-b9f5-7877d23e4a1f.png">

**Comment by jbloom** [comment]
@Bernadetadad, it actually does work here: in this case, it is showing the value with the lowest **magnitude**. That is why it is called *min_magnitude*.

Do you want me to also implement an option called *min* that just returns the absolute minimum? I can do that, but keep in mind that if you then have values like -0.1 and -5.3, it will return -5.3.

**Comment by jbloom** [comment]
@Bernadetadad, I just wanted to re-up this. Is the explanation above satisfactory and I can close this issue, or did you have some other statistic in mind to calculate and if so what?

**Comment by Bernadetadad** [comment]
yes, I'm closing it.
