### ISSUE TITLE
Add avg_prob_escape plots from each replicate to avg_antibody_escape notebooks

### ISSUE THREAD

**Issue by fwelsh** [dms-vep/dms-vep-pipeline#156]
I've noted that correlation between models for replicate selections is highly dependent on the concentrations used for modeling. If libA and libB are run at different _effective_ potencies, the correlations are poor. Because of issues with estimated titers, antibody saturation, etc. with the flu libraries, running libA and libB at the exact same serum concentrations results in slightly different avg_prob_escape values. I have to estimate a slightly higher set of concentrations for running libB.

It'd be useful to visualize the avg_prob_escape curves from all replicates in this notebook, so we can more easily take that into account when evaluating the model correlations and averaged result. @jbloom

**Comment by jbloom** [comment]
This is done in `dms-vep-pipeline-3`.
