### ISSUE TITLE
Store IC50s outside pickle file

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#167]
Would it be possible to store IC50/90 values somewhere outside pickle file as well. I want to use these for plotting ACE2 affinity correlations between various datasets but currently these are stored in .pickle files that are not tracked on github and since I'm working in a separate repo where I have several added other repos as submodules I can't access these unless I rerun the original repos again.

**Comment by jbloom** [comment]
Aren't these stored in files like this one?

https://github.com/dms-vep/dms-vep-pipeline/blob/main/test_example/results/antibody_escape/REGN10933_icXX_avg.csv

I think for this ACE2 analysis you should use IC50, not IC90.

**Comment by jbloom** [comment]
Closing this issue as we are now using `dms-vep-pipeline-3` anyway.
