### ISSUE TITLE
Functional data heatmap filtering

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#64]
Current functional data heatmaps can be filtered by max functional score. I don't particularly like this because even if just one amino acid in strongly positive in the site we end up filtering for such sites. I think it would be useful to be able to filter for sites that have a number of amino acids that have positive effects it seems like this would emphasize sites that have a lot potential to change. I'm not saying these options have to be mutually exclusive, but it an option would be nice.

Maybe this could be mean functional score filter, although I feel like then sites that have stop codons or deletions may be disadvantaged.

**Comment by jbloom** [comment]
Addressed in #72.
