### ISSUE TITLE
Sub-split repositories with specific data for publication

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#70]
Not pipeline issue _per se_ but might be applicable for multiple repos using `dms-vep`.
We need to figure out what is the best way of splitting off repositories when we want to make only subset of data (e.g. only some antibodies/sera) available for publication/sharing. Separate repos, git tags, etc.

**Comment by jbloom** [comment]
Here is the recommended procedure to split off a public copy of one of the repos for publication:

Instructions here for example case of splitting `SARS-CoV-2_Omicron_BA.1_spike_DMS` off to `SARS-CoV-2_Omicron_BA.1_spike_DMS_mAbs`

First, make a shallow clone with submodules into the repo with the desired new name:
```
git clone https://github.com/dms-vep/SARS-CoV-2_Omicron_BA.1_spike_DMS SARS-CoV-2_Omicron_BA.1_spike_DMS_mAbs --recurse-submodules --depth 1
```

Edit the `config.yaml` to update `github_repo` and `description` to match the new study.

Then rename the remote, such as:
```
git remote set-url origin https://github.com/dms-vep/SARS-CoV-2_Omicron_BA.1_spike_DMS_mAbs
```

Next, edit the input data in the `./data/` subdirectory to remove any undesired antibodies / datasets that are not part of the study.

Then remove the `docs` and `results` folders with
```
rm -rf docs results
```

Next re-run the `snakemake` pipeline.

Now we want to make this the new `main` branch and clear the history, so follow [here](https://stackoverflow.com/a/13102849):
```
git checkout --orphan newBranch
git add -A
git commit -m 'first public commit for this project split off private repo'
git branch -D main
git branch -m main
```

Then just create the repo on GitHub, push to it, set up GitHub pages, etc.
