### ISSUE TITLE
Do not rescale y-axis on escape line plot

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/dms-vep-pipeline#71]
On escape lineplots if you select smaller view window and move that window along the structure the y-axis re-scales based on the the max value within the current window view. The y-scale should probably be fixed to the max escape regardless of the view window, otherwise it gives misleading impression of high escape over small windows.

**Comment by jbloom** [comment]
I agree that this would be desirable, but I can't figure out how to do it while still allowing the y-axis metric to be dynamically chosen by dropdown (which I think is a more important feature). I think it might not be possible to set fixed scales with limits depending on another dropdown in `altair`.
