### ISSUE TITLE
Docs fail if there are any wildcards in repo-specific rules

### ISSUE THREAD

**Issue by caelanradford** [dms-vep/dms-vep-pipeline#85]
If there is a wildcard in a rule of the Snakemake file in the top level directory of a repo, it will cause the docs to fail. Rules with wildcards in the base pipeline are hard coded in `docs.smk`. I am currently getting around this by hard coding the new rules and wildcards into the `docs.smk` file of the base pipeline of my repo, but that is not a good way to do this going forward.

**Comment by jbloom** [comment]
I can fix this, but first you need to make `dms-vep-pipeline` a submodule in your main repo! It isn't a submodule right now, it's just part of the main repo. That makes it impossible to update separately, and is bad practice in general as you can no longer sync your `dms-vep-pipeline` subdirectory with the main pipeline.
