### ISSUE TITLE
500 : Internal Server Error when opening Jupyter Notebooks in dms-vep-pipeline environment

### ISSUE THREAD

**Issue by WillHannon-MCB** [dms-vep/dms-vep-pipeline#96]
@Caleb-Carr and I have run into the same issue when trying to open `.ipynb` files after we build the `dms-vep-pipeline` conda environment. We can run `jupyter` commands, but when we try to open `.ipynb` files, we get a `500 : Internal Server Error`. 

I believe that this error can be attributed to an issue with `nbconvert` and an incompatible version of `importlib_metadata` in the `python 3.9` standard library. 

1. @jbloom, have you recently built the `dms-vep-pipeline` environment from scratch and opened `.ipynb` files, or is this error isolated to us? I'm using the most recent version of conda: 
```
mamba 0.27.0
conda 22.9.0
```

2. Is there a reason that you've set `python==3.9` for the conda environment? Bumping python up to `==3.10` fixed the notebook issue for me.

**Comment by jbloom** [comment]
I don't think I'm getting this error, and not sure if @Bernadetadad or @Caleb-Carr are either. Maybe it could be solved by removing the `.ipynb_checkpoints` directory?

But if not, I'm fine in principle with upgrading to python 3.10. Just make a pull request if you want to do this.

**Comment by Bernadetadad** [comment]
I'm only ever opening notebooks on `dms-vep-pipeline` environment that is in the `BloomLab` and I don't have that issue.

**Comment by caelanradford** [comment]
I think this error is specific to jupyter notebooks and does not happen in jupyter lab. I started using jupyter lab to get around it.

**Comment by jbloom** [comment]
I think @caelanradford maybe has the right solution. Just use `jupyter lab` instead---does that fix it?

**Comment by WillHannon-MCB** [comment]
I get the same issue with `jupyter notebook` on both the bloom lab environment and mine.

**Mine:**
```
File "/home/whannon/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 137, in get_export_names
        exporters = sorted(e.name for e in entry_points(group="nbconvert.exporters"))
    TypeError: entry_points() got an unexpected keyword argument 'group'
```

**Bloom lab:**
```
File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 137, in get_export_names
        exporters = sorted(e.name for e in entry_points(group="nbconvert.exporters"))
    TypeError: entry_points() got an unexpected keyword argument 'group'
```

However, as per @caelanradford's good tip, you can get around this by using `jupyter lab`. That said, the same error is still showing up, it's just not throwing a `500: Internal Server Error` the prevents you from running the notebook.
